In [1]:
import pandas as pd

In [5]:
data = pd.read_csv(r"C:\Users\Sid\Desktop\Directed Study\PIE\pie-perf\improvement_pairs_additional_metadata.csv",sep="\t")

In [6]:
data

,user_id,problem_id,language,submission_id_v0,submission_id_v1,cpu_time_v0,cpu_time_v1,memory_v0,memory_v1,status_v0,status_v1,improvement_frac,code_v0,code_v1,code_v0_loc,code_v1_loc
0,u116766943,p00849,C++,s624998539,s546809015,9370.0,9250.0,1232.0,1228.0,Time Limit Exceeded,Time Limit Exceeded,1.28,"#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...","#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...",122.0,127.0
1,u116766943,p00849,C++,s546809015,s829771916,9250.0,8780.0,1228.0,1228.0,Time Limit Exceeded,Time Limit Exceeded,5.08,"#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...","#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...",127.0,125.0
2,u116766943,p00849,C++,s812631681,s154463767,8700.0,8030.0,1232.0,1232.0,Time Limit Exceeded,Time Limit Exceeded,7.70,"#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...","#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...",144.0,144.0
3,u116766943,p00849,C++,s363969251,s061168313,8500.0,920.0,1252.0,12164.0,Time Limit Exceeded,Accepted,89.18,"#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...","#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...",145.0,214.0
4,u116766943,p00849,C++,s061168313,s755775167,920.0,420.0,12164.0,9780.0,Accepted,Accepted,54.35,"#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...","#include<bits/stdc++.h>\n\n\n\n#define REP(i,s...",214.0,178.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551732,u952951927,p00728,C,s527097831,s418351707,20000.0,2110.0,596.0,596.0,Time Limit Exceeded,Time Limit Exceeded,89.45,#include <stdio.h>\n\n\n\nint main() {\n\n\n\n...,#include <stdio.h>\n\n\n\nint main() {\n\n\n\n...,36.0,46.0
551733,u952951927,p00728,C,s418351707,s990680233,2110.0,0.0,596.0,596.0,Time Limit Exceeded,Accepted,100.00,#include <stdio.h>\n\n\n\nint main() {\n\n\n\n...,#include <stdio.h>\n\n\n\nint main() {\n\n\n\n...,46.0,46.0
551734,u955830252,p00728,C,s974093801,s745674174,20000.0,0.0,600.0,600.0,Time Limit Exceeded,Accepted,100.00,#include <stdio.h>\n\n\n\nint main(){\n\n int...,#include <stdio.h>\n\n\n\nint main(){\n\n int...,23.0,23.0
551735,u962560616,p00728,C,s009070548,s049645259,20000.0,0.0,596.0,600.0,Time Limit Exceeded,Accepted,100.00,"#include <stdio.h>\n\nint main (){\n\n int n,...","#include <stdio.h>\n\nint main (){\n\n int n,...",45.0,45.0
551736,u979136186,p00728,C++,s235281404,s577569050,20000.0,0.0,1148.0,1160.0,Time Limit Exceeded,Accepted,100.00,#include<iostream>\n\n//#include<fstream>\n\n\...,#include<iostream>\n\n\n\nusing namespace std;...,43.0,41.0

In [8]:
data['language'].value_counts()

language
C++       317839
Python    187538
Java       29442
C          16918
Name: count, dtype: int64

In [43]:
local_error  = pd.read_json(r'C:\Users\Sid\Desktop\Directed Study\improve-code-efficiency\Results\filtered_running_pairs_1000_local.json',lines=True,orient='records')

In [44]:
local_error

,input,target,problem_id
0,"x=int(input())\n\nc=1\n\nfor b in range(1,x):\...","x=int(input())\n\nc=1\n\nfor b in range(1,x):\...",p03352
1,import sys\n\nimport math\n\n\n\ndef input():\...,import sys\n\nimport math\n\n\n\ndef input():\...,p03352
2,x = int(input())\n\ny = []\n\nfor i in range(1...,x = int(input())\n\ny = []\n\nfor i in range(1...,p03352
3,from itertools import product\n\n\n\n\n\ndef s...,"from math import floor, log, sqrt\n\n\n\n\n\nd...",p03352
4,"from math import floor, log, sqrt\n\n\n\n\n\nd...","from math import ceil, floor, log, sqrt\n\n\n\...",p03352
...,...,...,...
935,"x,y,z,k = map(int,input().split())\n\na = [int...","x,y,z,k = map(int,input().split())\n\na = [int...",p03078
936,"x,y,z,k = map(int,input().split())\n\na = [int...","x,y,z,k = map(int,input().split())\n\na = [int...",p03078
937,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,p03078
938,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,p03078
939,"X, Y, Z, K = map(int, input().split())\n\nA = ...","X, Y, Z, K = map(int, input().split())\n\nA = ...",p03078

In [45]:
babel_error  = pd.read_json(r'C:\Users\Sid\Desktop\Directed Study\improve-code-efficiency\Results\filtered_running_pairs_1000_babel.json',lines=True,orient='records')

In [46]:
babel_error

,input,target,problem_id
0,"x=int(input())\n\nc=1\n\nfor b in range(1,x):\...","x=int(input())\n\nc=1\n\nfor b in range(1,x):\...",p03352
1,import sys\n\nimport math\n\n\n\ndef input():\...,import sys\n\nimport math\n\n\n\ndef input():\...,p03352
2,x = int(input())\n\ny = []\n\nfor i in range(1...,x = int(input())\n\ny = []\n\nfor i in range(1...,p03352
3,from itertools import product\n\n\n\n\n\ndef s...,"from math import floor, log, sqrt\n\n\n\n\n\nd...",p03352
4,"from math import floor, log, sqrt\n\n\n\n\n\nd...","from math import ceil, floor, log, sqrt\n\n\n\...",p03352
...,...,...,...
933,"x,y,z,k = map(int,input().split())\n\na = [int...","x,y,z,k = map(int,input().split())\n\na = [int...",p03078
934,"x,y,z,k = map(int,input().split())\n\na = [int...","x,y,z,k = map(int,input().split())\n\na = [int...",p03078
935,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,p03078
936,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,p03078
937,"X, Y, Z, K = map(int, input().split())\n\nA = ...","X, Y, Z, K = map(int, input().split())\n\nA = ...",p03078

In [60]:
merged_df = pd.merge(babel_error, local_error, on=['input', 'target', 'problem_id'], how='outer', indicator=True)

merged_df['_merge'].unique()

['both', 'left_only', 'right_only']
Categories (3, object): ['left_only', 'right_only', 'both']

In [61]:
# Select rows where the indicator column is not equal to 'both'
different_rows = merged_df[merged_df['_merge'] == 'left_only']

# Drop the indicator column if not needed
different_rows = different_rows.drop(columns=['_merge'])

# Display the result
print(different_rows)

                                                input  \
47  X = int(input())\n\n\n\ndef han(X):\n\n  i = 1...

                                               target problem_id
47  l = [1, 4, 8, 9, 16, 25, 27, 32, 36, 49, 64, 8...     p03352

In [62]:
different_rows

,input,target,problem_id
47,X = int(input())\n\n\n\ndef han(X):\n\n i = 1...,"l = [1, 4, 8, 9, 16, 25, 27, 32, 36, 49, 64, 8...",p03352

In [65]:
# Select rows where the indicator column is not equal to 'both'
different_rows = merged_df[merged_df['_merge'] == 'right_only']

# Drop the indicator column if not needed
different_rows = different_rows.drop(columns=['_merge'])

# Display the result

                                                  input  \
1018  def solve(X, Y, Z, V, E, A):\n\n    dp = [[0.0...
1019  # -*- coding: utf-8 -*-\n\n# スペース区切りの整数の入力\n\n...
1020  #4\n\nx,y,z,k=map(int,input().split())\n\nlist...

                                                 target problem_id
1018  def solve(X, Y, Z, V, E, A):\n\n    dp = [[0.0...     p00232
1019  import numpy as np\n\nimport pprint\n\n\n\n#入力...     p03078
1020  X,Y,Z,K = map(int,input().split())\n\n\n\nA = ...     p03078

In [66]:
(different_rows)

,input,target,problem_id
1018,"def solve(X, Y, Z, V, E, A):\n\n dp = [[0.0...","def solve(X, Y, Z, V, E, A):\n\n dp = [[0.0...",p00232
1019,# -*- coding: utf-8 -*-\n\n# スペース区切りの整数の入力\n\n...,import numpy as np\n\nimport pprint\n\n\n\n#入力...,p03078
1020,"#4\n\nx,y,z,k=map(int,input().split())\n\nlist...","X,Y,Z,K = map(int,input().split())\n\n\n\nA = ...",p03078

In [67]:
common_rows = merged_df[merged_df['_merge'] == 'both']

# Drop the indicator column if not needed
# different_rows = different_rows.drop(columns=['_merge'])
common_rows

,input,target,problem_id,_merge
0,"x=int(input())\n\nc=1\n\nfor b in range(1,x):\...","x=int(input())\n\nc=1\n\nfor b in range(1,x):\...",p03352,both
1,"x=int(input())\n\nc=1\n\nfor b in range(1,x):\...","x=int(input())\n\nc=1\n\nfor b in range(1,x):\...",p03352,both
2,"x=int(input())\n\nc=1\n\nfor b in range(1,x):\...","x=int(input())\n\nc=1\n\nfor b in range(1,x):\...",p03352,both
3,"x=int(input())\n\nc=1\n\nfor b in range(1,x):\...","x=int(input())\n\nc=1\n\nfor b in range(1,x):\...",p03352,both
4,import sys\n\nimport math\n\n\n\ndef input():\...,import sys\n\nimport math\n\n\n\ndef input():\...,p03352,both
...,...,...,...,...
1013,"x,y,z,k = map(int,input().split())\n\na = [int...","x,y,z,k = map(int,input().split())\n\na = [int...",p03078,both
1014,"x,y,z,k = map(int,input().split())\n\na = [int...","x,y,z,k = map(int,input().split())\n\na = [int...",p03078,both
1015,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,p03078,both
1016,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,p03078,both
1017,"X, Y, Z, K = map(int, input().split())\n\nA = ...","X, Y, Z, K = map(int, input().split())\n\nA = ...",p03078,both

In [70]:
rows_in_df1_not_in_df2 = local_error[~local_error.isin(babel_error)].dropna()

# Display the result
# print("Rows present in df1 and not in df2:")
(rows_in_df1_not_in_df2)

,input,target,problem_id
171,"def solve(X, Y, Z, V, E, A):\n\n dp = [[0.0...","def solve(X, Y, Z, V, E, A):\n\n dp = [[0.0...",p00232
938,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,# -*- coding: utf-8 -*-\n\nfrom heapq import m...,p03078
939,"X, Y, Z, K = map(int, input().split())\n\nA = ...","X, Y, Z, K = map(int, input().split())\n\nA = ...",p03078

In [71]:
rows_in_df1_not_in_df2 = babel_error[~babel_error.isin(local_error)].dropna()

# Display the result
# print("Rows present in df1 and not in df2:")
(rows_in_df1_not_in_df2)

,input,target,problem_id
171,X = int(input())\n\n\n\nans = 0\n\nfor i in ra...,X = int(input())\n\n\n\nans = 1\n\nfor b in ra...,p03352

In [72]:
error_log_babble = pd.read_json(r'C:\Users\Sid\Desktop\Directed Study\improve-code-efficiency\Results\error_logs_total_1000_babel.json')

In [79]:
error_log_babble

                                                error  index     tag
0                                             Timeout      1   input
1                                             Timeout      3   input
2                                             Timeout      5   input
3                                             Timeout      9   input
4                                             Timeout     17   input
..                                                ...    ...     ...
73    File "<string>", line 105\n    print T[i]\n ...    627  target
74                                            Timeout    773   input
75    File "<string>", line 43\n    print L2[i]\n ...    846   input
76    File "<string>", line 43\n    print L[i]\n  ...    846  target
77  Traceback (most recent call last):\n  File "<s...    958  target

[78 rows x 3 columns]

In [87]:
set_babel = set(error_log_babble['index'].unique())

In [88]:
error_log_local = pd.read_json(r'C:\Users\Sid\Desktop\Directed Study\improve-code-efficiency\Results\error_logs_total_1000_local.json')

In [89]:
set_local = set(error_log_local['index'].unique())

In [90]:
len(error_log_local['index'].unique())

60

In [82]:
unique_error_index = error_log_babble.index.difference(error_log_local.index)
unique_error_index

RangeIndex(start=75, stop=78, step=1)

In [91]:
set_babel-set_local

{214, 535, 618}

In [92]:
set_local-set_babel

{58}

In [94]:
error_log_babble[error_log_babble['index']==214]

                                                error  index     tag
47  Traceback (most recent call last):\n  File "<s...    214   input
48  Traceback (most recent call last):\n  File "<s...    214  target

In [97]:
error_log_babble['error'].iloc[47]

'Traceback (most recent call last):\n  File "<string>", line 51, in <module>\nValueError: not enough values to unpack (expected 3, got 1)\n'

In [98]:
error_log_babble['error'].iloc[47]

'Traceback (most recent call last):\n  File "<string>", line 51, in <module>\nValueError: not enough values to unpack (expected 3, got 1)\n'

In [ ]:
err[error_log_local]